# Generated by Django 3.2.3 on 2021-05-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completeorder',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
