# Generated by Django 3.2.3 on 2021-06-13 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210613_0040'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompleteOrder',
        ),
    ]
