# Generated by Django 3.2.3 on 2021-05-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='photos/1.jpg', upload_to='photos'),
        ),
    ]
